- name: Add banner strings
  copy:
    dest: /etc/motd
    content: |
      ███╗   ███╗ █████╗ ██╗      ██████╗              
      ████╗ ████║██╔══██╗██║     ██╔═══██╗             
      ██╔████╔██║███████║██║     ██║   ██║             
      ██║╚██╔╝██║██╔══██║██║     ██║   ██║             
      ██║ ╚═╝ ██║██║  ██║███████╗╚██████╔╝             
      ╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝ ╚═════╝              
                                                      
      ██████╗  ██████╗ ██╗     ███████╗███████╗███████╗
      ██╔══██╗██╔═══██╗██║     ██╔════╝██╔════╝██╔════╝
      ██████╔╝██║   ██║██║     █████╗  ███████╗█████╗  
      ██╔═══╝ ██║   ██║██║     ██╔══╝  ╚════██║██╔══╝  
      ██║     ╚██████╔╝███████╗███████╗███████║███████╗
      ╚═╝      ╚═════╝ ╚══════╝╚══════╝╚══════╝╚══════╝

- name: Install pip
  apt:
    name: python3-pip
    update_cache: yes
    cache_valid_time: 3600

- name: Install jmespath python package
  pip:
    name: jmespath

- name: download app
  get_url:
    url: https://github.com/fteychene/prometheus-app-sample/releases/download/0.1.0/prometheus_metric_generator.jar
    dest: /home/{{user}}/prometheus_metric_generator.jar

- name: create service file
  template:
    src: prometheus-app.service.j2
    dest: /etc/systemd/system/prometheus-app.service

- name: start service
  systemd:
    state: started
    enabled: yes
    name: prometheus-app
    daemon_reload: yes